### ISSUE TITLE
I cannot start the app

### ISSUE THREAD

**Issue by pawnda** [matiastucci/ionic-ocr-example#5]
This is what i get, when i try to build the app...

[15:24:18] Finished 'sass' after 1.57 s
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/input/input-base.d.ts(2,10): Error TS2305: Module '"/Users/bru/Documents/project/ionic-ocr-example/node_modules/@angular/common/index"' has no exported member 'NgControl'.
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/input/input.d.ts(2,10): Error TS2305: Module '"/Users/bru/Documents/project/ionic-ocr-example/node_modules/@angular/common/index"' has no exported member 'NgControl'.
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/input/native-input.d.ts(2,10): Error TS2305: Module '"/Users/bru/Documents/project/ionic-ocr-example/node_modules/@angular/common/index"' has no exported member 'NgControl'.
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/modal/modal.d.ts(1,24): Error TS2305: Module '"/Users/bru/Documents/project/ionic-ocr-example/node_modules/@angular/core/index"' has no exported member 'DynamicComponentLoader'.
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/nav-controller.d.ts(1,28): Error TS2305: Module '"/Users/bru/Documents/project/ionic-ocr-example/node_modules/@angular/core/index"' has no exported member 'DynamicComponentLoader'.
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/nav-controller.d.ts(216,19): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/nav-controller.d.ts(295,15): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/nav-controller.d.ts(364,16): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/nav-controller.d.ts(415,39): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/nav-controller.d.ts(445,15): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/nav-portal.d.ts(1,40): Error TS2305: Module '"/Users/bru/Documents/project/ionic-ocr-example/node_modules/@angular/core/index"' has no exported member 'DynamicComponentLoader'.
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/nav-registry.d.ts(8,25): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/nav-registry.d.ts(9,25): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/nav.d.ts(1,40): Error TS2305: Module '"/Users/bru/Documents/project/ionic-ocr-example/node_modules/@angular/core/index"' has no exported member 'DynamicComponentLoader'.
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/nav.d.ts(121,11): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/view-controller.d.ts(23,20): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/nav/view-controller.d.ts(86,33): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/searchbar/searchbar.d.ts(2,10): Error TS2305: Module '"/Users/bru/Documents/project/ionic-ocr-example/node_modules/@angular/common/index"' has no exported member 'NgControl'.
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/segment/segment.d.ts(2,10): Error TS2305: Module '"/Users/bru/Documents/project/ionic-ocr-example/node_modules/@angular/common/index"' has no exported member 'NgControl'.
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/tabs/tab.d.ts(1,40): Error TS2305: Module '"/Users/bru/Documents/project/ionic-ocr-example/node_modules/@angular/core/index"' has no exported member 'DynamicComponentLoader'.
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/tabs/tab.d.ts(134,11): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/components/toggle/toggle.d.ts(2,10): Error TS2305: Module '"/Users/bru/Documents/project/ionic-ocr-example/node_modules/@angular/common/index"' has no exported member 'ControlValueAccessor'.
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/decorators/page.d.ts(12,24): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
TypeScript error: /Users/bru/Documents/project/ionic-ocr-example/node_modules/ionic-angular/decorators/page.d.ts(13,19): Error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
[15:24:23] Finished 'build' after 6.35 s
[15:24:23] Starting 'run:before'...
[15:24:23] Finished 'run:before' after 7.94 μs

**Comment by pawnda** [comment]
Dependencies are the problem.

**Comment by Bigous** [comment]
Hi @pawnda could you share how did you solve it?

**Comment by matiastucci** [comment]
@Bigous which version are you trying? 1 or 2?

**Comment by Bigous** [comment]
2

**Comment by matiastucci** [comment]
@Bigous: I just updated the whole project to ionic `2.0.0-rc.1` and now should be working fine

**Comment by Bigous** [comment]
Worked like a charm. Tks

**Comment by marko1943** [comment]
Guess there are new dependency issues again?
Didn't work for me, I had to create a new Ionic2 project and copy the relevant folders to make it work.
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
