### ISSUE TITLE
Not exactly data

### ISSUE THREAD

**Issue by anujsphinx** [matiastucci/ionic-ocr-example#6]
Hey,
  I checked this in Ionic View but it is showing some content not exactly content .Can you help me out that how would it provie exact data from business card .Sometime it is showing contact number sometime it is showing address and then garbage data

**Comment by matiastucci** [comment]
hi! that's an ocrad.js (the OCR framework I'm using) issue, not ionic or this starter. You can try an Ocrad demo [here](http://antimatter15.com/ocrad.js/demo.html).

**Comment by anujsphinx** [comment]
I checked that demo . Result is as following 
![orcard](https://cloud.githubusercontent.com/assets/17042493/21180545/86d2500a-c21f-11e6-8e17-cc1a12f7cece.PNG)

**Comment by matiastucci** [comment]
If that demo is not reading it well, my ionic app is not going to read it either. You can create an issue in Ocrad's repo tho.
