### ISSUE TITLE
window.OCRAD is not a function error

### ISSUE THREAD

**Issue by ihoudjedje** [matiastucci/ionic-ocr-example#8]
first of all, thanx so much for the library...
after fighting with dependencies, finally the project is running under `ionic serve`, but once i chose the option of scanning the image that already exists with the project **demo_image**, i got this error once i hit the button **scan**
i think the **orcad.js** file which is in the **lib** directry is not imported in the **home.ts** file.
Any help would be more than appertiated
![image](https://user-images.githubusercontent.com/16365985/27005221-01ed8454-4e1a-11e7-9502-9808c7a9b2b4.png)

**Comment by pinheirorb** [comment]
check that you have included the script in the index.html 

_**<script src ="assets/lib/ocrad.js"></ script>**_

**Comment by AnupamaPrasad** [comment]
I added 

<script src ="assets/lib/ocrad.js"></ script>

Still it's not working..!!! :( @pinheirorb

**Comment by YoussefTizi** [comment]
you want to install ocard.js
npm install ocrad.js

and you have included it into index.html
`  
  <ion-app></ion-app>

  <script src="cordova.js"></script>
  <script src ="assets/lib/ocrad.js"></script>
  
  <script src="build/polyfills.js"></script>

  
  <script src="build/vendor.js"></script>

  
  <script src="build/main.js"></script>
 `
